In [15]:
import numpy as np

arr = np.arange(1, 26).reshape(5, 5)

print("Matrix:\n", arr)
print("First Row:", arr[0])
print("Last Column:", arr[:, -1])
print("Diagonal Elements:", np.diag(arr))

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
Diagonal Elements: [ 1  7 13 19 25]


In [16]:

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Matrix Multiplication:\n", np.dot(A, B))

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:

arr = np.arange(1, 101)

print(arr[arr % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [18]:


arr = np.arange(1, 17).reshape(4, 4)

arr[arr % 2 == 0] = 0

print(arr)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [19]:


arr = np.random.randint(1, 100, (5, 5))

print("Matrix:\n", arr)
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))

Matrix:
 [[57 33 30 66 13]
 [57  7 63 91 59]
 [ 8 75 94 99 23]
 [ 6 89 84 30 38]
 [14 52 94 72 97]]
Maximum: 99
Minimum: 6
Mean: 54.04
Median: 57.0


In [20]:

arr = np.random.randint(1, 100, 20)

print("Original:", arr)
print("Ascending:", np.sort(arr))
print("Descending:", np.sort(arr)[::-1])

Original: [40 77 54 97 37 95 64 95  3 43 87 49  5 20 85 35 84 88 50 68]
Ascending: [ 3  5 20 35 37 40 43 49 50 54 64 68 77 84 85 87 88 95 95 97]
Descending: [97 95 95 88 87 85 84 77 68 64 54 50 49 43 40 37 35 20  5  3]


In [21]:

arr = np.arange(1, 37).reshape(6, 6)

print("Matrix:\n", arr)
print("Main Diagonal:", np.diag(arr))

print("Upper Triangular:\n", np.triu(arr))
print("Lower Triangular:\n", np.tril(arr))

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Main Diagonal: [ 1  8 15 22 29 36]
Upper Triangular:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Lower Triangular:
 [[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


In [22]:

arr = np.arange(1, 21)

print("4 x 5:\n", arr.reshape(4, 5))
print("2 x 10:\n", arr.reshape(2, 10))
print("5 x 4:\n", arr.reshape(5, 4))

4 x 5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2 x 10:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
5 x 4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [23]:

arr = np.arange(1, 26).reshape(5, 5)

print("Matrix:\n", arr)

print("Row Sum:", np.sum(arr, axis=1))
print("Column Sum:", np.sum(arr, axis=0))

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Row Sum: [ 15  40  65  90 115]
Column Sum: [55 60 65 70 75]


In [24]:

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

print("Common Elements:", np.intersect1d(arr1, arr2))

Common Elements: [4 5 6]


In [25]:

arr = np.random.randint(1, 100, (5, 5))

print("Matrix:\n", arr)

pos = np.unravel_index(np.argmax(arr), arr.shape)

print("Largest Element:", np.max(arr))
print("Position (row, column):", pos)

Matrix:
 [[47 21 69 21 48]
 [74 34 77 41 59]
 [ 4 52 93 34 33]
 [47 56 27 16 54]
 [43 47 14 25  8]]
Largest Element: 93
Position (row, column): (np.int64(2), np.int64(2))


In [26]:

marks = np.array([78, 85, 90, 65, 72, 88, 95, 80])

print("Marks:", marks)

highest = np.max(marks)
lowest = np.min(marks)
average = np.mean(marks)

print("Highest Marks:", highest)
print("Lowest Marks:", lowest)
print("Average Marks:", average)

print("Students Scoring Above Average:")
print(marks[marks > average])

Marks: [78 85 90 65 72 88 95 80]
Highest Marks: 95
Lowest Marks: 65
Average Marks: 81.625
Students Scoring Above Average:
[85 90 88 95]
